---
title: "git_00"
author: "Denise Sahagun"
date: "Spring  2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with a sequence of commits to the master branch.
Our project will be done using several commits to the master branch.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->
You are old," said the youth, "as I mentioned before,  
 And have grown most uncommonly fat;  
 Yet you turned a back-somersault in at the door —  
  Pray, what is the reason of that?"  
 "In my youth," said the sage, as he shook his grey locks,  
    

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->
Twas brillig, and the slithy toves  
Did gyre and gimble in the wabe:  
All mimsy were the borogoves,  
And the mome raths outgrabe.  
“Beware the Jabberwock, my son!  

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->
"The sun was shining on the sea,  
Shining with all his might:  
He did his very best to make  
The billows smooth and bright —  
And this was odd, because it was  

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->
'Tis the voice of the Lobster: I heard him declare  
"You have baked me too brown, I must sugar my hair."  
As a duck with its eyelids, so he with his nose  
Trims his belt and his buttons, and turns out his toes.  
When the sands are all dry, he is gay as a lark,  